services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=springboot_fullstack_challenge'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
